version: '3'
services:
  mongodb:
    image: "mongo:5"
    environment:
      MONGO_INITDB_DATABASE: quotesdb
    volumes:
    - ./data/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:Z
  web-quotes:
    build:
      context: .
      dockerfile: Containerfile
    image: tripledes/web-quotes:latest
    ports:
      - "8080:8080"